[package]
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["network-programming"]
description = "a client library to work with all file transfer protocols"
documentation = "https://docs.rs/ka-ching"
edition = "2018"
homepage = "https://veeso.github.io/ka-ching/"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["scp-client", "sftp-client", "ftp-client", "s3-client"]
license = "MIT"
name = "ka-ching"
readme = "README.md"
repository = "https://github.com/veeso/ka-ching"
version = "0.7.0"

[dependencies]
chrono = "0.4.19"
log = "0.4.14"
rust-s3 = { version = "0.27.0-rc4", default-features = false, features = [ "sync-native-tls", "sync" ], optional = true }
ssh2 = { version = "0.9.0", optional = true }
suppaftp = { version = "4.1.2", features = [ "secure" ], optional = true }
thiserror = "^1.0.0"
wildmatch = "2.0.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
tempfile = "3.1.0"

[features]
default = [ "ssh" ]
ftp = [ "suppaftp" ]
ssh = [ "ssh2" ]
s3 = [ "rust-s3" ]
github-actions = [ ]
with-s3-ci = []
with-containers = []

[target."cfg(target_family = \"unix\")"]
[target."cfg(target_family = \"unix\")".dependencies]
users = "0.11.0"

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.1.4"
